package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * AdminDetails generated by hbm2java
 */
public class AdminDetails  implements java.io.Serializable {


     private Integer idadminDetails;
     private String username;
     private String password;

    public AdminDetails() {
    }

    public AdminDetails(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdadminDetails() {
        return this.idadminDetails;
    }
    
    public void setIdadminDetails(Integer idadminDetails) {
        this.idadminDetails = idadminDetails;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


