package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * CategoryDetails generated by hbm2java
 */
public class CategoryDetails  implements java.io.Serializable {


     private Integer idcategoryDetails;
     private SubCategory subCategory;
     private TopCategory topCategory;
     private Product product;

    public CategoryDetails() {
    }

	
    public CategoryDetails(SubCategory subCategory, Product product) {
        this.subCategory = subCategory;
        this.product = product;
    }
    public CategoryDetails(SubCategory subCategory, TopCategory topCategory, Product product) {
       this.subCategory = subCategory;
       this.topCategory = topCategory;
       this.product = product;
    }
   
    public Integer getIdcategoryDetails() {
        return this.idcategoryDetails;
    }
    
    public void setIdcategoryDetails(Integer idcategoryDetails) {
        this.idcategoryDetails = idcategoryDetails;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public TopCategory getTopCategory() {
        return this.topCategory;
    }
    
    public void setTopCategory(TopCategory topCategory) {
        this.topCategory = topCategory;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


