package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer idcity;
     private String city;
     private Set customers = new HashSet(0);
     private Set suppliers = new HashSet(0);

    public City() {
    }

    public City(String city, Set customers, Set suppliers) {
       this.city = city;
       this.customers = customers;
       this.suppliers = suppliers;
    }
   
    public Integer getIdcity() {
        return this.idcity;
    }
    
    public void setIdcity(Integer idcity) {
        this.idcity = idcity;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }




}


