package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * CommisionRate generated by hbm2java
 */
public class CommisionRate  implements java.io.Serializable {


     private Integer idcommisionRate;
     private Double commision;

    public CommisionRate() {
    }

    public CommisionRate(Double commision) {
       this.commision = commision;
    }
   
    public Integer getIdcommisionRate() {
        return this.idcommisionRate;
    }
    
    public void setIdcommisionRate(Integer idcommisionRate) {
        this.idcommisionRate = idcommisionRate;
    }
    public Double getCommision() {
        return this.commision;
    }
    
    public void setCommision(Double commision) {
        this.commision = commision;
    }




}


