package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * CustomerFeedback generated by hbm2java
 */
public class CustomerFeedback  implements java.io.Serializable {


     private Integer idcustomerFeedback;
     private SystemDate systemDate;
     private Customer customer;
     private Supplier supplier;
     private String customerFeedback;

    public CustomerFeedback() {
    }

	
    public CustomerFeedback(SystemDate systemDate, Customer customer, Supplier supplier) {
        this.systemDate = systemDate;
        this.customer = customer;
        this.supplier = supplier;
    }
    public CustomerFeedback(SystemDate systemDate, Customer customer, Supplier supplier, String customerFeedback) {
       this.systemDate = systemDate;
       this.customer = customer;
       this.supplier = supplier;
       this.customerFeedback = customerFeedback;
    }
   
    public Integer getIdcustomerFeedback() {
        return this.idcustomerFeedback;
    }
    
    public void setIdcustomerFeedback(Integer idcustomerFeedback) {
        this.idcustomerFeedback = idcustomerFeedback;
    }
    public SystemDate getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(SystemDate systemDate) {
        this.systemDate = systemDate;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getCustomerFeedback() {
        return this.customerFeedback;
    }
    
    public void setCustomerFeedback(String customerFeedback) {
        this.customerFeedback = customerFeedback;
    }




}


