package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * CustomerBlacklist generated by hbm2java
 */
public class CustomerBlacklist  implements java.io.Serializable {


     private Integer idcustomerBlacklist;
     private Customer customer;

    public CustomerBlacklist() {
    }

    public CustomerBlacklist(Customer customer) {
       this.customer = customer;
    }
   
    public Integer getIdcustomerBlacklist() {
        return this.idcustomerBlacklist;
    }
    
    public void setIdcustomerBlacklist(Integer idcustomerBlacklist) {
        this.idcustomerBlacklist = idcustomerBlacklist;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


