package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String email;
     private SystemDate systemDate;
     private UserType userType;
     private Status status;
     private ImageData imageData;
     private City city;
     private Gender gender;
     private Salutation salutation;
     private String firstName;
     private String middleName;
     private String lastName;
     private String addressNo;
     private String addressStreet;
     private String addressStreet2;
     private String nicNumber;
     private Date dateOfBirth;
     private Integer contactNumber1;
     private Integer contactNumber2;
     private Set savedItemses = new HashSet(0);
     private Set customerFeedbacks = new HashSet(0);
     private Set ratings = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set customerLogins = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set customerRecovers = new HashSet(0);
     private Set customerBlacklists = new HashSet(0);
     private Set watchLists = new HashSet(0);
     private Set cartDetailses = new HashSet(0);
     private Set supplierFeedbacks = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String email, SystemDate systemDate, UserType userType, Status status, City city, Gender gender, Salutation salutation) {
        this.email = email;
        this.systemDate = systemDate;
        this.userType = userType;
        this.status = status;
        this.city = city;
        this.gender = gender;
        this.salutation = salutation;
    }
    public Customer(String email, SystemDate systemDate, UserType userType, Status status, ImageData imageData, City city, Gender gender, Salutation salutation, String firstName, String middleName, String lastName, String addressNo, String addressStreet, String addressStreet2, String nicNumber, Date dateOfBirth, Integer contactNumber1, Integer contactNumber2, Set savedItemses, Set customerFeedbacks, Set ratings, Set orderses, Set customerLogins, Set invoices, Set customerRecovers, Set customerBlacklists, Set watchLists, Set cartDetailses, Set supplierFeedbacks) {
       this.email = email;
       this.systemDate = systemDate;
       this.userType = userType;
       this.status = status;
       this.imageData = imageData;
       this.city = city;
       this.gender = gender;
       this.salutation = salutation;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.addressNo = addressNo;
       this.addressStreet = addressStreet;
       this.addressStreet2 = addressStreet2;
       this.nicNumber = nicNumber;
       this.dateOfBirth = dateOfBirth;
       this.contactNumber1 = contactNumber1;
       this.contactNumber2 = contactNumber2;
       this.savedItemses = savedItemses;
       this.customerFeedbacks = customerFeedbacks;
       this.ratings = ratings;
       this.orderses = orderses;
       this.customerLogins = customerLogins;
       this.invoices = invoices;
       this.customerRecovers = customerRecovers;
       this.customerBlacklists = customerBlacklists;
       this.watchLists = watchLists;
       this.cartDetailses = cartDetailses;
       this.supplierFeedbacks = supplierFeedbacks;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public SystemDate getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(SystemDate systemDate) {
        this.systemDate = systemDate;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public ImageData getImageData() {
        return this.imageData;
    }
    
    public void setImageData(ImageData imageData) {
        this.imageData = imageData;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public Salutation getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(Salutation salutation) {
        this.salutation = salutation;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddressNo() {
        return this.addressNo;
    }
    
    public void setAddressNo(String addressNo) {
        this.addressNo = addressNo;
    }
    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }
    public String getAddressStreet2() {
        return this.addressStreet2;
    }
    
    public void setAddressStreet2(String addressStreet2) {
        this.addressStreet2 = addressStreet2;
    }
    public String getNicNumber() {
        return this.nicNumber;
    }
    
    public void setNicNumber(String nicNumber) {
        this.nicNumber = nicNumber;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Integer getContactNumber1() {
        return this.contactNumber1;
    }
    
    public void setContactNumber1(Integer contactNumber1) {
        this.contactNumber1 = contactNumber1;
    }
    public Integer getContactNumber2() {
        return this.contactNumber2;
    }
    
    public void setContactNumber2(Integer contactNumber2) {
        this.contactNumber2 = contactNumber2;
    }
    public Set getSavedItemses() {
        return this.savedItemses;
    }
    
    public void setSavedItemses(Set savedItemses) {
        this.savedItemses = savedItemses;
    }
    public Set getCustomerFeedbacks() {
        return this.customerFeedbacks;
    }
    
    public void setCustomerFeedbacks(Set customerFeedbacks) {
        this.customerFeedbacks = customerFeedbacks;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getCustomerLogins() {
        return this.customerLogins;
    }
    
    public void setCustomerLogins(Set customerLogins) {
        this.customerLogins = customerLogins;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getCustomerRecovers() {
        return this.customerRecovers;
    }
    
    public void setCustomerRecovers(Set customerRecovers) {
        this.customerRecovers = customerRecovers;
    }
    public Set getCustomerBlacklists() {
        return this.customerBlacklists;
    }
    
    public void setCustomerBlacklists(Set customerBlacklists) {
        this.customerBlacklists = customerBlacklists;
    }
    public Set getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set watchLists) {
        this.watchLists = watchLists;
    }
    public Set getCartDetailses() {
        return this.cartDetailses;
    }
    
    public void setCartDetailses(Set cartDetailses) {
        this.cartDetailses = cartDetailses;
    }
    public Set getSupplierFeedbacks() {
        return this.supplierFeedbacks;
    }
    
    public void setSupplierFeedbacks(Set supplierFeedbacks) {
        this.supplierFeedbacks = supplierFeedbacks;
    }




}


