package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CustomerRecover generated by hbm2java
 */
public class CustomerRecover  implements java.io.Serializable {


     private Integer idcustomerRecover;
     private Customer customer;
     private String code;
     private Date updateDate;

    public CustomerRecover() {
    }

	
    public CustomerRecover(Customer customer) {
        this.customer = customer;
    }
    public CustomerRecover(Customer customer, String code, Date updateDate) {
       this.customer = customer;
       this.code = code;
       this.updateDate = updateDate;
    }
   
    public Integer getIdcustomerRecover() {
        return this.idcustomerRecover;
    }
    
    public void setIdcustomerRecover(Integer idcustomerRecover) {
        this.idcustomerRecover = idcustomerRecover;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


