package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * CustomerLogin generated by hbm2java
 */
public class CustomerLogin  implements java.io.Serializable {


     private Integer idcustomerLogin;
     private Customer customer;
     private String password;

    public CustomerLogin() {
    }

	
    public CustomerLogin(Customer customer) {
        this.customer = customer;
    }
    public CustomerLogin(Customer customer, String password) {
       this.customer = customer;
       this.password = password;
    }
   
    public Integer getIdcustomerLogin() {
        return this.idcustomerLogin;
    }
    
    public void setIdcustomerLogin(Integer idcustomerLogin) {
        this.idcustomerLogin = idcustomerLogin;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


