package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * Deliver generated by hbm2java
 */
public class Deliver  implements java.io.Serializable {


     private Integer iddeliver;
     private DeliverStatus deliverStatus;
     private Invoice invoice;
     private String firstName;
     private String lastName;
     private String addressNo;
     private String addressStreet;
     private String addressStreet2;
     private Integer contactNumber;
     private Integer contactNumber2;
     private String city;

    public Deliver() {
    }

	
    public Deliver(DeliverStatus deliverStatus, Invoice invoice) {
        this.deliverStatus = deliverStatus;
        this.invoice = invoice;
    }
    public Deliver(DeliverStatus deliverStatus, Invoice invoice, String firstName, String lastName, String addressNo, String addressStreet, String addressStreet2, Integer contactNumber, Integer contactNumber2, String city) {
       this.deliverStatus = deliverStatus;
       this.invoice = invoice;
       this.firstName = firstName;
       this.lastName = lastName;
       this.addressNo = addressNo;
       this.addressStreet = addressStreet;
       this.addressStreet2 = addressStreet2;
       this.contactNumber = contactNumber;
       this.contactNumber2 = contactNumber2;
       this.city = city;
    }
   
    public Integer getIddeliver() {
        return this.iddeliver;
    }
    
    public void setIddeliver(Integer iddeliver) {
        this.iddeliver = iddeliver;
    }
    public DeliverStatus getDeliverStatus() {
        return this.deliverStatus;
    }
    
    public void setDeliverStatus(DeliverStatus deliverStatus) {
        this.deliverStatus = deliverStatus;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddressNo() {
        return this.addressNo;
    }
    
    public void setAddressNo(String addressNo) {
        this.addressNo = addressNo;
    }
    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }
    public String getAddressStreet2() {
        return this.addressStreet2;
    }
    
    public void setAddressStreet2(String addressStreet2) {
        this.addressStreet2 = addressStreet2;
    }
    public Integer getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(Integer contactNumber) {
        this.contactNumber = contactNumber;
    }
    public Integer getContactNumber2() {
        return this.contactNumber2;
    }
    
    public void setContactNumber2(Integer contactNumber2) {
        this.contactNumber2 = contactNumber2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


