package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DeliverStatus generated by hbm2java
 */
public class DeliverStatus  implements java.io.Serializable {


     private Integer iddeliverStatus;
     private String deliverStatus;
     private Set delivers = new HashSet(0);

    public DeliverStatus() {
    }

    public DeliverStatus(String deliverStatus, Set delivers) {
       this.deliverStatus = deliverStatus;
       this.delivers = delivers;
    }
   
    public Integer getIddeliverStatus() {
        return this.iddeliverStatus;
    }
    
    public void setIddeliverStatus(Integer iddeliverStatus) {
        this.iddeliverStatus = iddeliverStatus;
    }
    public String getDeliverStatus() {
        return this.deliverStatus;
    }
    
    public void setDeliverStatus(String deliverStatus) {
        this.deliverStatus = deliverStatus;
    }
    public Set getDelivers() {
        return this.delivers;
    }
    
    public void setDelivers(Set delivers) {
        this.delivers = delivers;
    }




}


