package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender  implements java.io.Serializable {


     private Integer idgender;
     private String gender;
     private Set customers = new HashSet(0);

    public Gender() {
    }

    public Gender(String gender, Set customers) {
       this.gender = gender;
       this.customers = customers;
    }
   
    public Integer getIdgender() {
        return this.idgender;
    }
    
    public void setIdgender(Integer idgender) {
        this.idgender = idgender;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


