package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ImageData generated by hbm2java
 */
public class ImageData  implements java.io.Serializable {


     private Integer idimageData;
     private String path;
     private Set suppliers = new HashSet(0);
     private Set customers = new HashSet(0);

    public ImageData() {
    }

    public ImageData(String path, Set suppliers, Set customers) {
       this.path = path;
       this.suppliers = suppliers;
       this.customers = customers;
    }
   
    public Integer getIdimageData() {
        return this.idimageData;
    }
    
    public void setIdimageData(Integer idimageData) {
        this.idimageData = idimageData;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


