package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * InvoiceItems generated by hbm2java
 */
public class InvoiceItems  implements java.io.Serializable {


     private Integer idinvoiceItems;
     private Invoice invoice;
     private Product product;
     private Double amount;
     private Integer qty;
     private Double price;
     private Double sellierProfit;
     private Double profit;

    public InvoiceItems() {
    }

	
    public InvoiceItems(Invoice invoice, Product product) {
        this.invoice = invoice;
        this.product = product;
    }
    public InvoiceItems(Invoice invoice, Product product, Double amount, Integer qty, Double price, Double sellierProfit, Double profit) {
       this.invoice = invoice;
       this.product = product;
       this.amount = amount;
       this.qty = qty;
       this.price = price;
       this.sellierProfit = sellierProfit;
       this.profit = profit;
    }
   
    public Integer getIdinvoiceItems() {
        return this.idinvoiceItems;
    }
    
    public void setIdinvoiceItems(Integer idinvoiceItems) {
        this.idinvoiceItems = idinvoiceItems;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getSellierProfit() {
        return this.sellierProfit;
    }
    
    public void setSellierProfit(Double sellierProfit) {
        this.sellierProfit = sellierProfit;
    }
    public Double getProfit() {
        return this.profit;
    }
    
    public void setProfit(Double profit) {
        this.profit = profit;
    }




}


