package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private ProductStatus productStatus;
     private SystemDate systemDate;
     private Supplier supplier;
     private String productName;
     private Integer qty;
     private Double price;
     private Double sellingPrice;
     private Date exDate;
     private Date MDate;
     private String deiscription;
     private Integer sold;
     private Set invoiceItemses = new HashSet(0);
     private Set categoryDetailses = new HashSet(0);
     private Set watchLists = new HashSet(0);
     private Set savedItemses = new HashSet(0);
     private Set productImages = new HashSet(0);
     private Set productHasCartDetailses = new HashSet(0);

    public Product() {
    }

	
    public Product(ProductStatus productStatus, SystemDate systemDate, Supplier supplier) {
        this.productStatus = productStatus;
        this.systemDate = systemDate;
        this.supplier = supplier;
    }
    public Product(ProductStatus productStatus, SystemDate systemDate, Supplier supplier, String productName, Integer qty, Double price, Double sellingPrice, Date exDate, Date MDate, String deiscription, Integer sold, Set invoiceItemses, Set categoryDetailses, Set watchLists, Set savedItemses, Set productImages, Set productHasCartDetailses) {
       this.productStatus = productStatus;
       this.systemDate = systemDate;
       this.supplier = supplier;
       this.productName = productName;
       this.qty = qty;
       this.price = price;
       this.sellingPrice = sellingPrice;
       this.exDate = exDate;
       this.MDate = MDate;
       this.deiscription = deiscription;
       this.sold = sold;
       this.invoiceItemses = invoiceItemses;
       this.categoryDetailses = categoryDetailses;
       this.watchLists = watchLists;
       this.savedItemses = savedItemses;
       this.productImages = productImages;
       this.productHasCartDetailses = productHasCartDetailses;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public ProductStatus getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(ProductStatus productStatus) {
        this.productStatus = productStatus;
    }
    public SystemDate getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(SystemDate systemDate) {
        this.systemDate = systemDate;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public Date getExDate() {
        return this.exDate;
    }
    
    public void setExDate(Date exDate) {
        this.exDate = exDate;
    }
    public Date getMDate() {
        return this.MDate;
    }
    
    public void setMDate(Date MDate) {
        this.MDate = MDate;
    }
    public String getDeiscription() {
        return this.deiscription;
    }
    
    public void setDeiscription(String deiscription) {
        this.deiscription = deiscription;
    }
    public Integer getSold() {
        return this.sold;
    }
    
    public void setSold(Integer sold) {
        this.sold = sold;
    }
    public Set getInvoiceItemses() {
        return this.invoiceItemses;
    }
    
    public void setInvoiceItemses(Set invoiceItemses) {
        this.invoiceItemses = invoiceItemses;
    }
    public Set getCategoryDetailses() {
        return this.categoryDetailses;
    }
    
    public void setCategoryDetailses(Set categoryDetailses) {
        this.categoryDetailses = categoryDetailses;
    }
    public Set getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set watchLists) {
        this.watchLists = watchLists;
    }
    public Set getSavedItemses() {
        return this.savedItemses;
    }
    
    public void setSavedItemses(Set savedItemses) {
        this.savedItemses = savedItemses;
    }
    public Set getProductImages() {
        return this.productImages;
    }
    
    public void setProductImages(Set productImages) {
        this.productImages = productImages;
    }
    public Set getProductHasCartDetailses() {
        return this.productHasCartDetailses;
    }
    
    public void setProductHasCartDetailses(Set productHasCartDetailses) {
        this.productHasCartDetailses = productHasCartDetailses;
    }




}


