package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * ProductHasCartDetails generated by hbm2java
 */
public class ProductHasCartDetails  implements java.io.Serializable {


     private Integer idproductHasCartDetails;
     private SystemDate systemDate;
     private Status status;
     private Product product;
     private CartDetails cartDetails;
     private Integer qty;

    public ProductHasCartDetails() {
    }

	
    public ProductHasCartDetails(SystemDate systemDate, Status status, Product product, CartDetails cartDetails) {
        this.systemDate = systemDate;
        this.status = status;
        this.product = product;
        this.cartDetails = cartDetails;
    }
    public ProductHasCartDetails(SystemDate systemDate, Status status, Product product, CartDetails cartDetails, Integer qty) {
       this.systemDate = systemDate;
       this.status = status;
       this.product = product;
       this.cartDetails = cartDetails;
       this.qty = qty;
    }
   
    public Integer getIdproductHasCartDetails() {
        return this.idproductHasCartDetails;
    }
    
    public void setIdproductHasCartDetails(Integer idproductHasCartDetails) {
        this.idproductHasCartDetails = idproductHasCartDetails;
    }
    public SystemDate getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(SystemDate systemDate) {
        this.systemDate = systemDate;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public CartDetails getCartDetails() {
        return this.cartDetails;
    }
    
    public void setCartDetails(CartDetails cartDetails) {
        this.cartDetails = cartDetails;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


