package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * ProductImage generated by hbm2java
 */
public class ProductImage  implements java.io.Serializable {


     private Integer idproductImage;
     private Product product;
     private String productImagePath;

    public ProductImage() {
    }

	
    public ProductImage(Product product) {
        this.product = product;
    }
    public ProductImage(Product product, String productImagePath) {
       this.product = product;
       this.productImagePath = productImagePath;
    }
   
    public Integer getIdproductImage() {
        return this.idproductImage;
    }
    
    public void setIdproductImage(Integer idproductImage) {
        this.idproductImage = idproductImage;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getProductImagePath() {
        return this.productImagePath;
    }
    
    public void setProductImagePath(String productImagePath) {
        this.productImagePath = productImagePath;
    }




}


