package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ProductStatus generated by hbm2java
 */
public class ProductStatus  implements java.io.Serializable {


     private Integer idproductStatus;
     private String productStatus;
     private Set products = new HashSet(0);

    public ProductStatus() {
    }

    public ProductStatus(String productStatus, Set products) {
       this.productStatus = productStatus;
       this.products = products;
    }
   
    public Integer getIdproductStatus() {
        return this.idproductStatus;
    }
    
    public void setIdproductStatus(Integer idproductStatus) {
        this.idproductStatus = idproductStatus;
    }
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


