package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private int idrating;
     private Customer customer;
     private Supplier supplier;
     private Integer rate;

    public Rating() {
    }

	
    public Rating(int idrating, Customer customer, Supplier supplier) {
        this.idrating = idrating;
        this.customer = customer;
        this.supplier = supplier;
    }
    public Rating(int idrating, Customer customer, Supplier supplier, Integer rate) {
       this.idrating = idrating;
       this.customer = customer;
       this.supplier = supplier;
       this.rate = rate;
    }
   
    public int getIdrating() {
        return this.idrating;
    }
    
    public void setIdrating(int idrating) {
        this.idrating = idrating;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }




}


