package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * SavedItems generated by hbm2java
 */
public class SavedItems  implements java.io.Serializable {


     private Integer idsavedItems;
     private Customer customer;
     private Product product;

    public SavedItems() {
    }

    public SavedItems(Customer customer, Product product) {
       this.customer = customer;
       this.product = product;
    }
   
    public Integer getIdsavedItems() {
        return this.idsavedItems;
    }
    
    public void setIdsavedItems(Integer idsavedItems) {
        this.idsavedItems = idsavedItems;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


