package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ShipingDetails generated by hbm2java
 */
public class ShipingDetails  implements java.io.Serializable {


     private Integer idshipingDetails;
     private String city;
     private Double cost;
     private Set invoices = new HashSet(0);

    public ShipingDetails() {
    }

    public ShipingDetails(String city, Double cost, Set invoices) {
       this.city = city;
       this.cost = cost;
       this.invoices = invoices;
    }
   
    public Integer getIdshipingDetails() {
        return this.idshipingDetails;
    }
    
    public void setIdshipingDetails(Integer idshipingDetails) {
        this.idshipingDetails = idshipingDetails;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


