package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer idstatus;
     private String status;
     private Set suppliers = new HashSet(0);
     private Set customers = new HashSet(0);
     private Set productHasCartDetailses = new HashSet(0);

    public Status() {
    }

    public Status(String status, Set suppliers, Set customers, Set productHasCartDetailses) {
       this.status = status;
       this.suppliers = suppliers;
       this.customers = customers;
       this.productHasCartDetailses = productHasCartDetailses;
    }
   
    public Integer getIdstatus() {
        return this.idstatus;
    }
    
    public void setIdstatus(Integer idstatus) {
        this.idstatus = idstatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getProductHasCartDetailses() {
        return this.productHasCartDetailses;
    }
    
    public void setProductHasCartDetailses(Set productHasCartDetailses) {
        this.productHasCartDetailses = productHasCartDetailses;
    }




}


