package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer idsubCategory;
     private String subCategory;
     private Set categoryDetailses = new HashSet(0);

    public SubCategory() {
    }

    public SubCategory(String subCategory, Set categoryDetailses) {
       this.subCategory = subCategory;
       this.categoryDetailses = categoryDetailses;
    }
   
    public Integer getIdsubCategory() {
        return this.idsubCategory;
    }
    
    public void setIdsubCategory(Integer idsubCategory) {
        this.idsubCategory = idsubCategory;
    }
    public String getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }
    public Set getCategoryDetailses() {
        return this.categoryDetailses;
    }
    
    public void setCategoryDetailses(Set categoryDetailses) {
        this.categoryDetailses = categoryDetailses;
    }




}


