package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private String email;
     private SystemDate systemDate;
     private UserType userType;
     private Status status;
     private ImageData imageData;
     private City city;
     private String supplierName;
     private String addressNo;
     private String addressStreet;
     private String addressStreet2;
     private Integer contactNumber;
     private Integer contactNumber2;
     private String companyName;
     private String companyRegNumber;
     private String supplierNic;
     private Integer ownerContactno;
     private Set orderses = new HashSet(0);
     private Set ratings = new HashSet(0);
     private Set supplierLogins = new HashSet(0);
     private Set supplierBlacklists = new HashSet(0);
     private Set customerFeedbacks = new HashSet(0);
     private Set supplierRecovers = new HashSet(0);
     private Set supplierFeedbacks = new HashSet(0);
     private Set products = new HashSet(0);

    public Supplier() {
    }

	
    public Supplier(String email, SystemDate systemDate, UserType userType, Status status, City city) {
        this.email = email;
        this.systemDate = systemDate;
        this.userType = userType;
        this.status = status;
        this.city = city;
    }
    public Supplier(String email, SystemDate systemDate, UserType userType, Status status, ImageData imageData, City city, String supplierName, String addressNo, String addressStreet, String addressStreet2, Integer contactNumber, Integer contactNumber2, String companyName, String companyRegNumber, String supplierNic, Integer ownerContactno, Set orderses, Set ratings, Set supplierLogins, Set supplierBlacklists, Set customerFeedbacks, Set supplierRecovers, Set supplierFeedbacks, Set products) {
       this.email = email;
       this.systemDate = systemDate;
       this.userType = userType;
       this.status = status;
       this.imageData = imageData;
       this.city = city;
       this.supplierName = supplierName;
       this.addressNo = addressNo;
       this.addressStreet = addressStreet;
       this.addressStreet2 = addressStreet2;
       this.contactNumber = contactNumber;
       this.contactNumber2 = contactNumber2;
       this.companyName = companyName;
       this.companyRegNumber = companyRegNumber;
       this.supplierNic = supplierNic;
       this.ownerContactno = ownerContactno;
       this.orderses = orderses;
       this.ratings = ratings;
       this.supplierLogins = supplierLogins;
       this.supplierBlacklists = supplierBlacklists;
       this.customerFeedbacks = customerFeedbacks;
       this.supplierRecovers = supplierRecovers;
       this.supplierFeedbacks = supplierFeedbacks;
       this.products = products;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public SystemDate getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(SystemDate systemDate) {
        this.systemDate = systemDate;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public ImageData getImageData() {
        return this.imageData;
    }
    
    public void setImageData(ImageData imageData) {
        this.imageData = imageData;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
    public String getAddressNo() {
        return this.addressNo;
    }
    
    public void setAddressNo(String addressNo) {
        this.addressNo = addressNo;
    }
    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }
    public String getAddressStreet2() {
        return this.addressStreet2;
    }
    
    public void setAddressStreet2(String addressStreet2) {
        this.addressStreet2 = addressStreet2;
    }
    public Integer getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(Integer contactNumber) {
        this.contactNumber = contactNumber;
    }
    public Integer getContactNumber2() {
        return this.contactNumber2;
    }
    
    public void setContactNumber2(Integer contactNumber2) {
        this.contactNumber2 = contactNumber2;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyRegNumber() {
        return this.companyRegNumber;
    }
    
    public void setCompanyRegNumber(String companyRegNumber) {
        this.companyRegNumber = companyRegNumber;
    }
    public String getSupplierNic() {
        return this.supplierNic;
    }
    
    public void setSupplierNic(String supplierNic) {
        this.supplierNic = supplierNic;
    }
    public Integer getOwnerContactno() {
        return this.ownerContactno;
    }
    
    public void setOwnerContactno(Integer ownerContactno) {
        this.ownerContactno = ownerContactno;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }
    public Set getSupplierLogins() {
        return this.supplierLogins;
    }
    
    public void setSupplierLogins(Set supplierLogins) {
        this.supplierLogins = supplierLogins;
    }
    public Set getSupplierBlacklists() {
        return this.supplierBlacklists;
    }
    
    public void setSupplierBlacklists(Set supplierBlacklists) {
        this.supplierBlacklists = supplierBlacklists;
    }
    public Set getCustomerFeedbacks() {
        return this.customerFeedbacks;
    }
    
    public void setCustomerFeedbacks(Set customerFeedbacks) {
        this.customerFeedbacks = customerFeedbacks;
    }
    public Set getSupplierRecovers() {
        return this.supplierRecovers;
    }
    
    public void setSupplierRecovers(Set supplierRecovers) {
        this.supplierRecovers = supplierRecovers;
    }
    public Set getSupplierFeedbacks() {
        return this.supplierFeedbacks;
    }
    
    public void setSupplierFeedbacks(Set supplierFeedbacks) {
        this.supplierFeedbacks = supplierFeedbacks;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


