package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SupplierRecover generated by hbm2java
 */
public class SupplierRecover  implements java.io.Serializable {


     private Integer idsupplierRecover;
     private Supplier supplier;
     private String code;
     private Date updateDate;

    public SupplierRecover() {
    }

	
    public SupplierRecover(Supplier supplier) {
        this.supplier = supplier;
    }
    public SupplierRecover(Supplier supplier, String code, Date updateDate) {
       this.supplier = supplier;
       this.code = code;
       this.updateDate = updateDate;
    }
   
    public Integer getIdsupplierRecover() {
        return this.idsupplierRecover;
    }
    
    public void setIdsupplierRecover(Integer idsupplierRecover) {
        this.idsupplierRecover = idsupplierRecover;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


