package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * SupplierFeedback generated by hbm2java
 */
public class SupplierFeedback  implements java.io.Serializable {


     private Integer idsupplierFeedback;
     private Customer customer;
     private Supplier supplier;
     private String supplierFeedback;

    public SupplierFeedback() {
    }

	
    public SupplierFeedback(Customer customer, Supplier supplier) {
        this.customer = customer;
        this.supplier = supplier;
    }
    public SupplierFeedback(Customer customer, Supplier supplier, String supplierFeedback) {
       this.customer = customer;
       this.supplier = supplier;
       this.supplierFeedback = supplierFeedback;
    }
   
    public Integer getIdsupplierFeedback() {
        return this.idsupplierFeedback;
    }
    
    public void setIdsupplierFeedback(Integer idsupplierFeedback) {
        this.idsupplierFeedback = idsupplierFeedback;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getSupplierFeedback() {
        return this.supplierFeedback;
    }
    
    public void setSupplierFeedback(String supplierFeedback) {
        this.supplierFeedback = supplierFeedback;
    }




}


