package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * SupplierBlacklist generated by hbm2java
 */
public class SupplierBlacklist  implements java.io.Serializable {


     private Integer idsupplierBlacklist;
     private Supplier supplier;

    public SupplierBlacklist() {
    }

    public SupplierBlacklist(Supplier supplier) {
       this.supplier = supplier;
    }
   
    public Integer getIdsupplierBlacklist() {
        return this.idsupplierBlacklist;
    }
    
    public void setIdsupplierBlacklist(Integer idsupplierBlacklist) {
        this.idsupplierBlacklist = idsupplierBlacklist;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }




}


