package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SystemDate generated by hbm2java
 */
public class SystemDate  implements java.io.Serializable {


     private Integer idsystemDate;
     private Date sysDate;
     private Set suppliers = new HashSet(0);
     private Set cartDetailses = new HashSet(0);
     private Set products = new HashSet(0);
     private Set customers = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set customerFeedbacks = new HashSet(0);
     private Set watchLists = new HashSet(0);
     private Set productHasCartDetailses = new HashSet(0);

    public SystemDate() {
    }

    public SystemDate(Date sysDate, Set suppliers, Set cartDetailses, Set products, Set customers, Set invoices, Set customerFeedbacks, Set watchLists, Set productHasCartDetailses) {
       this.sysDate = sysDate;
       this.suppliers = suppliers;
       this.cartDetailses = cartDetailses;
       this.products = products;
       this.customers = customers;
       this.invoices = invoices;
       this.customerFeedbacks = customerFeedbacks;
       this.watchLists = watchLists;
       this.productHasCartDetailses = productHasCartDetailses;
    }
   
    public Integer getIdsystemDate() {
        return this.idsystemDate;
    }
    
    public void setIdsystemDate(Integer idsystemDate) {
        this.idsystemDate = idsystemDate;
    }
    public Date getSysDate() {
        return this.sysDate;
    }
    
    public void setSysDate(Date sysDate) {
        this.sysDate = sysDate;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }
    public Set getCartDetailses() {
        return this.cartDetailses;
    }
    
    public void setCartDetailses(Set cartDetailses) {
        this.cartDetailses = cartDetailses;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getCustomerFeedbacks() {
        return this.customerFeedbacks;
    }
    
    public void setCustomerFeedbacks(Set customerFeedbacks) {
        this.customerFeedbacks = customerFeedbacks;
    }
    public Set getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set watchLists) {
        this.watchLists = watchLists;
    }
    public Set getProductHasCartDetailses() {
        return this.productHasCartDetailses;
    }
    
    public void setProductHasCartDetailses(Set productHasCartDetailses) {
        this.productHasCartDetailses = productHasCartDetailses;
    }




}


