package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TopCategory generated by hbm2java
 */
public class TopCategory  implements java.io.Serializable {


     private Integer idtopCategory;
     private String topCategory;
     private Set categoryDetailses = new HashSet(0);

    public TopCategory() {
    }

    public TopCategory(String topCategory, Set categoryDetailses) {
       this.topCategory = topCategory;
       this.categoryDetailses = categoryDetailses;
    }
   
    public Integer getIdtopCategory() {
        return this.idtopCategory;
    }
    
    public void setIdtopCategory(Integer idtopCategory) {
        this.idtopCategory = idtopCategory;
    }
    public String getTopCategory() {
        return this.topCategory;
    }
    
    public void setTopCategory(String topCategory) {
        this.topCategory = topCategory;
    }
    public Set getCategoryDetailses() {
        return this.categoryDetailses;
    }
    
    public void setCategoryDetailses(Set categoryDetailses) {
        this.categoryDetailses = categoryDetailses;
    }




}


