package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer iduserType;
     private String userType;
     private Set customers = new HashSet(0);
     private Set suppliers = new HashSet(0);

    public UserType() {
    }

    public UserType(String userType, Set customers, Set suppliers) {
       this.userType = userType;
       this.customers = customers;
       this.suppliers = suppliers;
    }
   
    public Integer getIduserType() {
        return this.iduserType;
    }
    
    public void setIduserType(Integer iduserType) {
        this.iduserType = iduserType;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }




}


