package POJOs;
// Generated Oct 3, 2017 6:37:39 PM by Hibernate Tools 3.6.0



/**
 * WatchList generated by hbm2java
 */
public class WatchList  implements java.io.Serializable {


     private Integer idwatchList;
     private SystemDate systemDate;
     private Customer customer;
     private Product product;

    public WatchList() {
    }

    public WatchList(SystemDate systemDate, Customer customer, Product product) {
       this.systemDate = systemDate;
       this.customer = customer;
       this.product = product;
    }
   
    public Integer getIdwatchList() {
        return this.idwatchList;
    }
    
    public void setIdwatchList(Integer idwatchList) {
        this.idwatchList = idwatchList;
    }
    public SystemDate getSystemDate() {
        return this.systemDate;
    }
    
    public void setSystemDate(SystemDate systemDate) {
        this.systemDate = systemDate;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


